### ISSUE TITLE
Websocket connections do not get deleted

### ISSUE THREAD

**Issue by showierdata9978** [meower-media/server#117]
When a client disconnects, there is a chance for the socket handler to not cause on close, so cloudlink is unable to delete the clients websocket connection.

In meower, this leads to always online (until restart) users or bots. Where the user or bot is unable to login to there account. Meower returns a internal error

When a socket is not deleted and you try to interact with it, it raises an error saying the client is closed. 

Possible fix:
  Catch the error and delete the client object and update ulist

**Comment by MikeDev101** [comment]
This is a design flaw with Cloudlink 3's underlying websocket framework. 

We are continuing to make strides towards the CL4 port. With CL4 utilizing a radically different underlying websocket framework, this issue is of less concern. 

On top of that, this issue is of extremely low probability of ever occurring, and (even if it does) you can always reconnect and try again.

Marking as won't fix, since this will be automatically rectified in the CL4 port.

**Comment by showierdata9978** [comment]
i have an account stuck in this state. @CodeBot, try interacting with it. the only way to clear it is restarting the server


This is essentially like banning a user, but they cant be unbanned

**Comment by showierdata9978** [comment]
i was also planning on fixing this myself, should be clear because i self assigned

**Comment by JoshAtticus** [comment]
> This is a design flaw with Cloudlink 3's underlying websocket framework.

Yeah, we know CL3 has issues, but that's no excuse not to fix them

> We are continuing to make strides towards the CL4 port. With CL4 utilizing a radically different underlying websocket framework, this issue is of less concern.

Or will it, have you tested?

> On top of that, this issue is of extremely low probability of ever occurring, and (even if it does) you can always reconnect and try again.

You can't just reconnect, because the session is still there

> Marking as won't fix, since this will be automatically rectified in the CL4 port.

But you haven't tested, how would you know

**Comment by tnix100** [comment]
huh, I'm re-opening this because yeah it's an issue

but @JoshAtticus this will be rectified in CL4 port anyway because CL4 allows multiple clients from a single user and has a much more reliable underlying websocket server

**Comment by showierdata9978** [comment]
And il go fix it
RIGHT NOW

**Comment by JoshAtticus** [comment]
> huh, I'm re-opening this because yeah it's an issue
> 
> but @JoshAtticus this will be rectified in CL4 port anyway because CL4 allows multiple clients from a single user and has a much more reliable underlying websocket server

But if it does happen in CL4, then accounts will still work, but you'll have a bunch of ghost connections that don't actually exist.

**Comment by tnix100** [comment]
> > huh, I'm re-opening this because yeah it's an issue
> > but @JoshAtticus this will be rectified in CL4 port anyway because CL4 allows multiple clients from a single user and has a much more reliable underlying websocket server
> 
> But if it does happen in CL4, then accounts will still work, but you'll have a bunch of ghost connections that don't actually exist.

well, yeah, it'll basically be a memory-leak but it won't affect anything

and if we spot a memory-leak then we'll need to fix it

**Comment by showierdata9978** [comment]
thats basicly what this is

**Comment by showierdata9978** [comment]
mb.py alerted me that this issue is still kicking around

![Screenshot_20230413-143244](https://user-images.githubusercontent.com/68120127/231864446-bca51081-10a4-449c-9257-95a0cef882cc.png)

https://github.com/meower-community/MeowerBot.py/blob/master/MeowerBot/Bot.py#L207

**Comment by tnix100** [comment]
This has been resolved.
