### ISSUE TITLE
[main | latest] Issue with user search queries

### ISSUE THREAD

**Issue by Bloctans** [meower-media/server#136]
every page after 3 i believe for me atleast has the last 9 or so user querys be the same every time. may be different on other devices, an example of this is on the bettermeower 1.5.0 branch. or the diference between https://api.meower.org/search/users?autoget&page=15&q= and https://api.meower.org/search/users?autoget&page=14&q=

**Comment by MikeDev101** [comment]
Should be fixed in the CL4 port. De-prioritizing issue.

**Comment by williamhorning** [comment]
at this point this shouldn't be an issue, so unless you reproduce it on the current server, i'm going to close this
