### ISSUE TITLE
[develop | latest] Bump the emoji limit per group chat to 250 emojis

### ISSUE THREAD

**Issue by NotFenixio** [meower-media/server#266]
Hi,
After some consideration, we think 100 emojis per GC may be a bit limiting.
Our suggestion is to bump this limit to 250 emojis instead.
I know this sounds a bit extreme, but hear us out:
- This would require creating less GCs, and possibly less accounts.
- cat: 500 * 150 > 250 * 200 (better than discord) (250*200 is assuming you have nitro and are paying $10000/month to boost all your servers to tier 3)
- noodles: more emojis = more better

**Comment by tnix100** [comment]
How about 250? That should be plenty for most groups, clients won't have to worry about "windowing" their emoji picker as much, and I was planning on increasing the group limit soon anyway, so we'll still beat Discord.

**Comment by NotFenixio** [comment]
Sounds fair to me!
