### ISSUE TITLE
add pronouns to user profiles

### ISSUE THREAD

**Issue by showierdata9978** [meower-media/server#272]
**Is your feature request related to a problem? Please describe.**
Not knowing what other people's pronouns are. Because you should never assume someone's pronouns.

**Describe the solution you'd like**
A new field on the user object that is structured like this:
```
{
   pronouns: [
          ["he", "him"],
          ["they", "them"]
   ]
}
```

This should also be on the partial user object so clients can render it inline if wanted. 

**Describe alternatives you've considered**
none.

**Comment by tnix100** [comment]
This doesn't seem like a necessary feature in my opinion. People should just use their quotes, and you can always ask what someone's pronouns are.

**Comment by showierdata9978** [comment]
> Assignee: ShowierData9978

**Comment by commandc904** [comment]
clients being able to render pronouns inline/under usernames would be great
also puts meowers features more in line with other platforms

**Comment by mybearworld** [comment]
> This doesn't seem like a necessary feature in my opinion. People should just use their quotes, and you can always ask what someone's pronouns are.

Looking into the quote every time you want to refer to someone is impractical. Most people don't have any pronouns there anyways.

**Comment by tnix100** [comment]
Fair enough then. Feel free to make a PR for this feature.

**Comment by showierdata9978** [comment]
ig not happening then because I'm not going to accept a single string

**Comment by williamhorning** [comment]
you don't get to close issues just because you don't like the way they'll be solved

**Comment by showierdata9978** [comment]
I get to close my own suggestions
