### ISSUE TITLE
[1| now] Pronouns

### ISSUE THREAD

**Issue by 3r1s-s** [meower-media/server#288]
maybe have a string in the user profile

**Comment by showierdata9978** [comment]
dupe

**Comment by 3r1s-s** [comment]
![87377263_123x123](https://github.com/user-attachments/assets/77655eb5-d3bc-475d-b4e2-a3c4d1d322d5)

**Comment by JoshAtticus** [comment]
I think https://github.com/meower-media/server/issues/291 is a more complete feature request

**Comment by 3r1s-s** [comment]
you'd be correct i'm just being annoying
