### ISSUE TITLE
[develop] Allow login to the web socket with multiple tokens

### ISSUE THREAD

**Issue by Finley224** [meower-media/server#304]
**Is your feature request related to a problem? Please describe.**
I am building a service with that lets you make a Meower bot and then host it on my servers, at the moment, I would have to log in to the web socket once for each bot. This uses unnecessary server resources for both Meower and my server.

**Describe the solution you'd like**
Allow logging into the web socket with more than one token, so you can get the dm's for multiple accounts at the same time. This could be in the form of a parameter, but instead of just taking a string, it could take a list of tokens or a command could be sent to log in with an additional token. If the web socket part of the server is still in python, I would be happy to help with adding this.

**Comment by tnix100** [comment]
I understand the frustration of needing multiple WebSocket connections. But we'd honestly prefer separate WebSocket connections, this way we can split up load between more servers making it easier to host Meower overall.

**Comment by Finley224** [comment]
> I understand the frustration of needing multiple WebSocket connections. But we'd honestly prefer separate WebSocket connections, this way we can split up load between more servers making it easier to host Meower overall.

ok, that is understandable, let me send you a dm and explain what I want to do so I can see if there is a way to do this that puts less load on meower.

**Comment by Finley224** [comment]
I will close this pr for now @tnix100

**Comment by Finley224** [comment]
Wrong status

**Comment by Finley224** [comment]
wrong status
